name: Our server will have linted, formatted and tested after every commit

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: pnpm adding
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: install dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test
      - name: formatting code
        run: pnpm run format
      - name: linting code
        run: pnpm run lint
      - name: Install Snyk CLI
        run: pnpm install -g snyk
      - name: Snyk test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: snyk/actions/setup@master
  #     - name: setup nodejs
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "22"
  #         cache: "npm"
  #     - name: Install Snyk CLI
  #       run: npm install -g snyk
  #     - name: Snyk test
  #       run: snyk test
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
